import { Jogos } from './../services/interfaces/jogo.interface';
// Generated by https://quicktype.io

export interface Jogos {
    idJogo:     number;
    tituloJogo: string;
    descJogo:   string;
    tagsJogo:   string;
    imagem1:    string;
    imagem2:    string;
    imagem3:    string;
    imagem4:    string;
}
